# Generated by Django 3.1.7 on 2023-01-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20230118_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_name',
            new_name='class_id',
        ),
    ]
